apps/customer/urls.py
from django.urls import path
from .views import (HomePageView, FoodSearchView,
                    CartPageView, CartAddView, CartRemoveView,
                    OrderCreateView, OrderDetailView, OrderPayView)

app_name = "customer"

urlpatterns =[
    path("", HomePageView.as_view(), name= "home"),
    path("foods/", FoodSearchView.as_view(), name="food-result"),

    path("cart/", CartPageView.as_view(), name="cart-page"),

    path("add-cart/<int:token>/", CartAddView.as_view(), name="cart-add"),
    path("remove-cart/<int:token>/", CartRemoveView.as_view(), name="cart-remove"),

    path("add-order/", OrderCreateView.as_view(), name="order-create"),
    path("order-detail/<str:order_id>/", OrderDetailView.as_view(), name="order-detail"),
    path("pay-order/<str:order_id>/", OrderPayView.as_view(), name="order-pay"),


]

apps/restaurant/urls.py
from django.urls import path
from .views.restaurant import (RegisterRestaurantView,
                                     RestaurantProfileView, DashBoardRestaurant, RestaurantRequestListView,
                                     RestaurantRequestStatusView, RestaurantDeleteView, RestaurantOrderList, ItemPreparedView, 
                                     OrderArrived)
from .views.food import (FoodCreateView, FoodDetailView, FoodListView, FoodDeleteView)

app_name = "restaurant"


urlpatterns = [
    path("", DashBoardRestaurant.as_view(), name="restaurant-dashboard"),
    path("foods/", FoodListView.as_view(), name="food-list"),

    path("register/", RegisterRestaurantView.as_view(), name="register-restaurant"),
    path("add-food/", FoodCreateView.as_view(), name="add-food"),
    path("delete-food/<str:token>/", FoodDeleteView.as_view(), name="delete-food"),
    path("requests/", RestaurantRequestListView.as_view(), name='restaurant-request-list'),
    path('restaurant-status/<str:restaurant_token>/<str:status>/', RestaurantRequestStatusView.as_view(), name="restaurant-status"),
    
    path("delete-restaurant/<str:token>/", RestaurantDeleteView.as_view(), name="delete-restaurant"),

    path("food-detail/<str:token>/", FoodDetailView.as_view(), name="food-detail"),
    path("profile/<str:token>/", RestaurantProfileView.as_view(), name="restaurant-profile"),

    path('orders/', RestaurantOrderList.as_view(), name= "restaurant-orders"),
    path('item-prepared/<int:id>/', ItemPreparedView.as_view(), name="item-prepared"),
    path('order-arrived/<int:order_id>/', OrderArrived.as_view(), name="food-arrived"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import login, logout, signup


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),

    path("login/", login, name="account_login"), 
    path("logout/", logout, name="account_logout"), 
    path("signup/", signup, name="account_signup"), 

    path('', include("customer.urls")),
    path('restaurant/', include("restaurant.urls")),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.customer.views.handler404'
handler500 = 'apps.customer.views.handler500'

apps/customer/models.py
from django.db import models
from restaurant.models import Food
from django.contrib.auth import get_user_model
from accounts.utils.token_generator import random_number


class Order(models.Model):
    
    class status(models.TextChoices):
        ordered = "Ordered"
        preparing = "Preparing"
        sending = "Sending"
        arrived = "Arrived"

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    order_id = models.CharField(max_length=15, default=random_number)

    is_paid = models.BooleanField(default=False)

    date_created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=status.choices, default=status.ordered, max_length=10)

    @property
    def total_price(self):        
        total = sum(item.price() for item in self.items.all())
        return total

    def __str__(self):
        return str(self.order_id)


class OrderItem(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    item = models.ForeignKey(Food, on_delete=models.CASCADE)

    quantity = models.IntegerField(default=1)
    
    prepared = models.BooleanField(default=False)

    def price(self):
        return self.item.price * self.quantity

    def __str__(self):
        return self.order.order_id

apps/customer/views.py
from django.views.generic import TemplateView, ListView, View, DetailView
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import  messages
from django.db.models import Count

from restaurant.models import Food, Category
from customer.models import Order, OrderItem

from .cart import Cart

class HomePageView(TemplateView):
    '''
        Home page
    '''
    template_name = "customer/home.html"
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        
        context['categories'] = Category.objects.annotate(
                                                count=Count('food_category__id')
                                                ).order_by('-count')[:5]
        return context


class CartPageView(View):
    '''
        Show user orders
    '''

    def get(self, request):
        cart = Cart(request)
        orders = Order.objects.filter(user= request.user)
        return render(request, "customer/cart.html", {'cart': cart, "orders" : orders})


class CartAddView(LoginRequiredMixin, View):
    '''Add sth to cart (sessions)'''

    def get(self, request, token):
        cart = Cart(request)
        food = get_object_or_404(Food, token=token)

        if request.user == food.provider.owner:
            messages.success(self.request, "You can not order your restaurants food.", "warning")
            return redirect('restaurant:food-detail', token=food.token)

        if food.is_available:
            cart.add(food, 1)
            messages.success(self.request, "Food added to your cart", "success")
            return redirect('restaurant:food-detail', token=food.token)

        messages.success(self.request, "Sorry, this item is unavailable", "danger")
        return redirect('restaurant:food-detail', token=food.token)


class CartRemoveView(View):
    """Remove an item from cart"""

    def get(self, request, token):
        cart = Cart(request)
        food = get_object_or_404(Food, token=token)
        cart.remove(food)
        messages.success(self.request, "Item removed from your cart")
        return redirect('customer:cart-page')



class OrderCreateView(LoginRequiredMixin, View):
    '''Create a new order'''

    def get(self, request):
        cart = Cart(request)

        if cart:
            order = Order.objects.create(user=request.user)
            for item in cart:
                try:
                    OrderItem.objects.create(order=order, item=item['product'], quantity=item['quantity'])
                except:
                    pass

            cart.clear()
            messages.success(self.request, "Order created successfully", "success")
            return redirect("customer:cart-page")

        messages.success(self.request, "Cart is empty.", "warning")
        return redirect("customer:cart-page")


class OrderDetailView(LoginRequiredMixin, DetailView):
    # show detail of an order
    template_name = "customer/order-detail.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user == self.get_object().user:
            return super().dispatch(request, *args, **kwargs)
        
        return redirect("customer:home")

    def get_object(self):
        return get_object_or_404(Order, order_id=self.kwargs["order_id"])
    
    def get_context_data(self, **kwargs):        
        data = super().get_context_data(**kwargs)
        data["items"] = self.get_object().items.all()
        return data


class OrderPayView(LoginRequiredMixin, View):
    """
        Pay for an order. 
    """

    def get(self, request, order_id):
        order = get_object_or_404(Order, order_id= order_id, user=self.request.user)
        order.is_paid = True
        order.status = "preparing"
        order.save()
        
        for item in order.items.all():
            item.item.inventory -= item.quantity
            item.item.save()
        
        messages.success(self.request, "Order is paid now, wait for preparation proccess.", "success")
        return redirect("customer:cart-page")


class FoodSearchView(LoginRequiredMixin, ListView):
    '''
        Show result of searched data
    '''
    template_name = "customer/food-list.html"
    context_object_name = "foods"

    def dispatch(self, request, *args, **kwargs):
        self.user = self.request.user.profile.first()

        if self.user.city and self.user.country:
            return super().dispatch(request, *args, **kwargs)

        messages.success(request, "First you should update your profile.", "warning")
        return redirect("accounts:profile")

    def get_queryset(self):
        q = self.request.GET.get('q', None)

        food = Food.objects.select_related("provider").filter(
            Q(name__icontains=q) & Q(provider__country=self.user.country) | Q(Q(category__title=q))
        ).order_by("inventory")

        food_filtered_by_city = food.filter(Q(provider__city=self.user.city))

        if food_filtered_by_city:
            return food_filtered_by_city

        return food



def handler404 (request, exception):
    return render(request, "errors/404.html", {})

def handler500 (request, exception=None):
    return render(request, "errors/500.html", {})

apps/customer/templates/customer/cart.html
{% extends '_base.html' %}

{% block title %}Cart page{% endblock title %}

{% block body %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">total</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
     {% for item in cart %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.product }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.total_price }}</td>
            <td>
                <a href="{% url  'restaurant:food-detail' item.product.token  %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                  <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                </svg>
            </a>

                <a href="{% url 'customer:cart-remove' item.product.token %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            </a>
            </td>
        </tr>
        {% endfor %}

      <tr>
          <td>Total</td>
          <td colspan="4"></td>
          <td>{{cart.get_total_price}}</td>
      </tr>
      </tbody>
    </table>
    <a class="btn btn-success" href="{% url 'customer:order-create'  %}" style="color: white;">Order</a>
    {% if orders %}
    <hr><br><h5>Orders</h5> <br>
        {% for order in orders %}
            <a href="{% url 'customer:order-detail' order.order_id %}"><h6>{{order.order_id}}</h6></a> <br><hr>
        {% endfor %}
    {% endif %}

{% endblock body %}

apps/customer/templates/customer/food-list.html
{% extends '_base.html' %}

{% block title %}Result{% endblock title %}

{% block body %}
{% if foods %}
  {% for food in foods %}
  <div class="card" style="width: 18rem; display:inline-block;">
    {% if food.picture %}<img class="card-img-top" src="{{food.picture.url}}" width="70px;" height="250px;">{% endif %}

    <div class="card-body">
      <h5 class="card-title">{{food.name}}</h5>
      <p class="card-text">Provider: <a class="card-text" href="{% url 'restaurant:restaurant-profile' food.provider.token %}">{{food.provider}}</a></p>
      <p class="card-text">Price: {{food.price}}$</p>
      <p>Status: {% if food.is_available %}Avaiable{% else %}Unavailable{%endif%}</p>
        <a href="{{ food.get_absolute_url }}" class="btn btn-secondary">Detail</a>
    </div>
  </div>
  {% endfor %}
{% else %}
 <h1>No results found</h1>
{% endif %}
{% endblock body %}

apps/customer/templates/customer/home.html
{% extends '_base.html' %}

{% block title %}Django Food Store{% endblock title %}

{% block body %}
<br>
<div class="row height d-flex justify-content-center align-items-center">
        <h2 >Search for your favorite food</h2>
      <div class="col-md-8">
          <br>
           <form action="{% url 'customer:food-result'  %}"  method="get">{% csrf_token %}
               <div class="input-group">
                  <input name="q" type="text" class="form-control" placeholder="Search the food name or category..." >
                  <button class="btn btn-primary">Search</button>
              </div>
           </form>
      </div>
    </div>
<br>
<br>
<h2 align="center">Popular Categories</h2> <br>
<center>
    {% for category in categories %}
            <a href="{% url 'customer:food-result' %}?q={{category}}" class="btn btn-primary ">{{category}}</a>
    {% empty %}
        <h5>No category registered yet.</h5>
    {% endfor %}
</center>
{% endblock body %}

apps/customer/templates/customer/order-detail.html
{% extends '_base.html' %}

{% block title %}{{object.order_id}}{% endblock title %}

{% block body %}
<br>
<h4>Order id: {{object.order_id}}</h4> <hr>
<h4>Total price: {{object.total_price}}$</h4> <hr>

<h4>Items:</h4> <small>{% for item in items %} <a href="{% url 'restaurant:food-detail' item.item.token %}">{{item.item}}</a> {%endfor%}</small> <hr>    

{% if not object.is_paid %}
<a href="{% url 'customer:order-pay'  object.order_id %}" class="btn btn-success">Pay {{object.total_price}}$</a>


{% else %}
    <h4>Status: {{object.status}}</h4>
    {% if object.status == 'Sending' %}
        <a class="btn btn-success" href="{% url 'restaurant:food-arrived' object.order_id %}">Arrived</a>
    {% endif %}
{% endif %}

{% endblock body %}