apps/accounts/urls.py
from django.urls import path
from .views import (ProfileView, MoneyView, RequestCreateView,
                                     RequestListView, RequestDetailView, RequestStatusView)

app_name = "accounts"

urlpatterns = [
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile/<int:id>/", ProfileView.as_view(), name='profile'),
    path("exchange/", MoneyView.as_view(), name="exchange-money"), 

    path("add-request/", RequestCreateView.as_view(), name="add-request"),
    path('request-list/', RequestListView.as_view(), name="request-list"),
    path('request-detail/<str:token>/', RequestDetailView.as_view(), name="request-detail"),
    path('request-status/<int:request_token>/<str:status>/', RequestStatusView.as_view(), name="request-status")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import login, logout, signup


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),

    path("login/", login, name="account_login"), 
    path("logout/", logout, name="account_logout"), 
    path("signup/", signup, name="account_signup"), 

    path('', include("customer.urls")),
    path('restaurant/', include("restaurant.urls")),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.customer.views.handler404'
handler500 = 'apps.customer.views.handler500'

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

from .managers import UserManager
from .utils.validators import validate_file_size
from .utils.token_generator import random_number


class User(AbstractUser):
    '''Base user class'''

    class Role(models.TextChoices):
        '''User Role'''
        SUPERUSER = ("s", "Superuser")
        ADMIN = ("a", "Admin")
        NORMAL = ("n", "Normal")
        BLOCKED = ("b", "Blocked")

    username = None
    email = models.EmailField(max_length=200, unique=True)
    userid = models.IntegerField(unique=True, blank=True, null=True)
    balance = models.PositiveIntegerField(default=0)
    role = models.CharField(max_length=1, choices=Role.choices, default=Role.NORMAL)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    

    def __str__(self):
        return self.email

    @property
    def is_blocked(self):
        return bool(self.role == self.Role.BLOCKED)
    
    @property
    def is_admin(self):
        return bool(self.role in ["s", "a"])

    
class Profile(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="profile")

    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)

    country = models.CharField(max_length=120)
    city = models.CharField(max_length=120)
    detailed_address = models.CharField(max_length=200)

    phone_regex = RegexValidator(regex="\(?\d{3}\)?-? *\d{3}-? *-?\d{4}", 
                                message="Phone number format must be like: (XXX) XXX XXXX")
                                
    phone_number = models.CharField(max_length=15, validators=[phone_regex])

    passport_number = models.CharField(max_length=10)

    
    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class Request(models.Model):
    '''A model for requesting to become admin'''
    
    class Status(models.TextChoices):
        '''Request Status'''

        PENDING = ("p", "pending")
        ACCEPTED = ("a", "Accepted")
        REJECTED = ("r", "Rejected")
        BLOCKED = ("b", "Blocked")


    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="requests")
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.PENDING)

    attachment = models.FileField(upload_to="users/requests", 
                                validators=[validate_file_size], blank=True, null=True)
    
    date = models.DateTimeField(auto_now_add=True)
    
    description = models.TextField(blank=True, null=True)
    token = models.CharField(max_length=15, default=random_number)


    def __str__(self) -> str:
        return str(self.token)

apps/accounts/forms.py
from django import forms
from accounts.models import User, Request

import random

class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("email", "password")
    
    def save(self, commit= True): 
        user = super(RegisterUserForm, self).save(commit = False)
        user.userid = random.randint(1, 99999999999999)

        if commit:
            user.save()
            
        return user


class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ["attachment", "description"]
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(RequestForm, self).__init__(*args, **kwargs)
    
    def save(self, commit=True):
        request = super().save(commit=False)
        request.user = self.user
        request = request.save()
        return request

apps/accounts/views.py
from django.views.generic import UpdateView, View, FormView, ListView
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import  messages

from accounts.models import Profile as ProfileModel, Request
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RequestForm


class ProfileView(LoginRequiredMixin, UpdateView):
    '''
        Profile page. 
        Only the profile owner can update this page.
    '''

    template_name = "account/profile.html"
    context_object_name = "profile"

    fields = ["first_name", "last_name", "country", "city", 
                "detailed_address", "phone_number", "passport_number"]

    def get_object(self):
        # return users profile if there wasnt an id
        try:
             userid = self.kwargs["id"]

        except:
             return get_object_or_404(ProfileModel, 
                        user=self.request.user)
        
        return get_object_or_404(ProfileModel, 
                user__userid=userid)
    
    def get_success_url(self) -> str:
        return reverse_lazy("accounts:profile", 
                    kwargs={"id" : self.kwargs.get("id")})


class MoneyView(LoginRequiredMixin, View):
    '''You should implement payment method in here.'''
    
    def get(self, request):
        request.user.balance = request.user.balance + 20
        request.user.save()
        return HttpResponse("20 coins added to your balance.")


class RequestCreateView(LoginRequiredMixin, FormView):
    '''Request to become admin'''

    def dispatch(self, request, *args, **kwargs):
        '''Admin users can blocked users can not add request.'''

        # admin users can not request to become an admin
        if self.request.user.is_admin:
            messages.success(self.request, "You are already an admin.")
            return redirect("customer:home")
        
        # check if user is blocked or even there is a blocked request
        elif self.request.user.is_blocked or self.request.user.requests.filter(status="b"):
            messages.success(self.request, "Blocked users can not request.")
            return redirect("customer:home")
        
        # check if user has a pending request
        elif self.request.user.requests.filter(status="p"):
            messages.success(self.request, "You have already a pending request.")
            return redirect("customer:home")
        
        return super().dispatch(request, *args, **kwargs)
    

    template_name = "request/request-add.html"
    form_class = RequestForm
    success_url = reverse_lazy("customer:home")


    def get_form_kwargs(self):
        kwargs = super(RequestCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Request sent, wait for results.")
        return super(RequestCreateView, self).form_valid(form)
        
        
class RequestListView(LoginRequiredMixin, ListView):
    '''
        List of requests.
        Admins see all requests.
        Normal Users just see their own requests
    '''

    template_name = "request/request-list.html"
    context_object_name = "requests"

    def get_queryset(self):
        if self.request.user.is_admin:
            return Request.objects.filter(status="p")

        return Request.objects.filter(user=self.request.user)


class RequestDetailView(LoginRequiredMixin, UpdateView):
    '''
        Request detail page.
        Admins and request owner can access this page.
        Admins can accept/decline/block this request 
        Request owner can see or update(When its pending).
    '''

    def dispatch(self, request, *args, **kwargs):
        '''Admin users and request owner can access this page.'''

        if self.request.user.is_admin or self.get_object().user == self.request.user:
            return super().dispatch(request, *args, **kwargs)

        messages.success(self.request, "You can not access this page.")
        return redirect("customer:home")

    template_name = "request/request-update.html"
    fields = ["attachment", "description"]
    
    def get_object(self):
        return get_object_or_404(Request, token=self.kwargs["token"])
    
    def get_success_url(self):
        return reverse_lazy("accounts:request-detail",
                            kwargs={"token" : self.kwargs.get("token")})
    
    def post(self, request, *args, **kwargs):
        '''Check if user is trying to update a pending request.'''

        if self.get_object().status == "p" \
            and self.get_object().user == self.request.user:

            messages.success(self.request, "Request status updated.")
            return super().post(request, *args, **kwargs)

        messages.success(self.request, "You can only update requests with pending status.")
        return redirect("customer:home")


class RequestStatusView(LoginRequiredMixin, View):
    '''Change a requests status (accept, decline or block)'''
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_admin:
            return super().dispatch(request, *args, **kwargs)
        
        if not self.kwargs["status"] in ["a", "r", "b"]:
            messages.success(self.request, "Please insert a valid operation.")
            return redirect("customer:home")
        
        messages.success(self.request, "Only admin users can access this page.")
        return redirect("customer:home")
    

    def get(self, request, request_token, status):
        request = get_object_or_404(Request, token=request_token, status="p")

        request.status = status
        if status == "a":
            request.user.role = "a"

        request.save()
        request.user.save()

        messages.success(self.request, f"Request status changed to {status}.")
        return redirect("accounts:request-list")

apps/accounts/templates/request/request-add.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Admin Request{% endblock title %}

{% block body %}
<h2>Admin Request</h2>
<p style="color: red;">Upload your attachments and write a little description about yourself.</p> <hr>

<form method="post" enctype='multipart/form-data'>
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Request</button>
</form>
{% endblock body %}

apps/accounts/templates/request/request-list.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Request List{% endblock title %}

{% block body %}
<h2>Request List</h2><a href="{% url 'accounts:add-request' %}">New request</a>
 <hr>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Status</th>
        <th scope="col">Date</th>
        <th scope="col">Detail</th>
      </tr>
    </thead>
    <tbody>
      {% for request in requests %}
        <tr>
            <th scope="row">1</th>
            <td><a href="{% url 'accounts:profile' request.user.userid %}">{{ request.user }}</a></td>
            <td>{{ request.get_status_display  }}</td>
            <td>{{ request.date }}</td>
            <td><center><a class="btn btn-secondary" href="{% url 'accounts:request-detail' request.token %}">
                          {{ request.token }}</a></center></td>
        </tr>
      {% empty %}
        <h3>No request available.</h3>
      {% endfor %}
    </tbody>
  </table>

{% endblock body %}

apps/accounts/templates/request/request-update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ request.token }}{% endblock %}

{% block body %}
<h3>{{ request.token }}</h3>
<hr>

<div class="container">
    <h5>User: <a href="{% url 'accounts:profile' request.user.userid %}">{{ request.user }}</a></h5>
    <h5>Status: {{ request.get_status_display }}</h5>
    {% if request.attachment %}
        <h5>Attachment: <a href="{{ request.attachment.url }}">Click here</a></h5>
    {% endif %}
    <hr>
    <p>Description: <br> {{ request.description }}</p><hr>
    
    {% if user.is_admin and request.status == 'p'%}
        <a class="btn btn-success" href="{% url 'accounts:request-status' request.token 'a' %}">Accept</a>
        <a class="btn btn-danger" href="{% url 'accounts:request-status' request.token 'r' %}">Decline</a>
        <a class="btn btn-secondary" href="{% url 'accounts:request-status' request.token 'b' %}">Block</a>
        <hr>
    {% endif %}

    {% if user == request.user and request.status == 'p' %}
        <h3>Update</h3><hr>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Update</button>
        </form>

    {% endif %}
</div>

{% endblock body %}