apps/accounts/urls.py
from django.urls import path
from .views import (ProfileView, MoneyView, RequestCreateView,
                                     RequestListView, RequestDetailView, RequestStatusView)

app_name = "accounts"

urlpatterns = [
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile/<int:id>/", ProfileView.as_view(), name='profile'),
    path("exchange/", MoneyView.as_view(), name="exchange-money"), 

    path("add-request/", RequestCreateView.as_view(), name="add-request"),
    path('request-list/', RequestListView.as_view(), name="request-list"),
    path('request-detail/<str:token>/', RequestDetailView.as_view(), name="request-detail"),
    path('request-status/<int:request_token>/<str:status>/', RequestStatusView.as_view(), name="request-status")
]

apps/customer/urls.py
from django.urls import path
from .views import (HomePageView, FoodSearchView,
                    CartPageView, CartAddView, CartRemoveView,
                    OrderCreateView, OrderDetailView, OrderPayView)

app_name = "customer"

urlpatterns =[
    path("", HomePageView.as_view(), name= "home"),
    path("foods/", FoodSearchView.as_view(), name="food-result"),

    path("cart/", CartPageView.as_view(), name="cart-page"),

    path("add-cart/<int:token>/", CartAddView.as_view(), name="cart-add"),
    path("remove-cart/<int:token>/", CartRemoveView.as_view(), name="cart-remove"),

    path("add-order/", OrderCreateView.as_view(), name="order-create"),
    path("order-detail/<str:order_id>/", OrderDetailView.as_view(), name="order-detail"),
    path("pay-order/<str:order_id>/", OrderPayView.as_view(), name="order-pay"),


]

apps/restaurant/urls.py
from django.urls import path
from .views.restaurant import (RegisterRestaurantView,
                                     RestaurantProfileView, DashBoardRestaurant, RestaurantRequestListView,
                                     RestaurantRequestStatusView, RestaurantDeleteView, RestaurantOrderList, ItemPreparedView, 
                                     OrderArrived)
from .views.food import (FoodCreateView, FoodDetailView, FoodListView, FoodDeleteView)

app_name = "restaurant"


urlpatterns = [
    path("", DashBoardRestaurant.as_view(), name="restaurant-dashboard"),
    path("foods/", FoodListView.as_view(), name="food-list"),

    path("register/", RegisterRestaurantView.as_view(), name="register-restaurant"),
    path("add-food/", FoodCreateView.as_view(), name="add-food"),
    path("delete-food/<str:token>/", FoodDeleteView.as_view(), name="delete-food"),
    path("requests/", RestaurantRequestListView.as_view(), name='restaurant-request-list'),
    path('restaurant-status/<str:restaurant_token>/<str:status>/', RestaurantRequestStatusView.as_view(), name="restaurant-status"),
    
    path("delete-restaurant/<str:token>/", RestaurantDeleteView.as_view(), name="delete-restaurant"),

    path("food-detail/<str:token>/", FoodDetailView.as_view(), name="food-detail"),
    path("profile/<str:token>/", RestaurantProfileView.as_view(), name="restaurant-profile"),

    path('orders/', RestaurantOrderList.as_view(), name= "restaurant-orders"),
    path('item-prepared/<int:id>/', ItemPreparedView.as_view(), name="item-prepared"),
    path('order-arrived/<int:order_id>/', OrderArrived.as_view(), name="food-arrived"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import login, logout, signup


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),

    path("login/", login, name="account_login"), 
    path("logout/", logout, name="account_logout"), 
    path("signup/", signup, name="account_signup"), 

    path('', include("customer.urls")),
    path('restaurant/', include("restaurant.urls")),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.customer.views.handler404'
handler500 = 'apps.customer.views.handler500'

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Bookstore{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  {% include 'navbar.html' %}
  {% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
  {% endif %}
  <div class="container">
    {% block body %}
    {% endblock body %}
  </div>
  <!-- JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4\
     mb-3 bg-white border-bottom shadow-sm">
      <a href="{% url 'customer:home' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">FoodStore</a>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
                  <a class="dropdown-item" href="{% url 'accounts:exchange-money' %}">Exchange</a>
                    {% if request.user.add_food %}
                        <a class="dropdown-item" href="{% url 'restaurant:restaurant-dashboard' %}">Dashboard</a>
                    {% endif %}

                    <a class="dropdown-item" href="{% url 'customer:cart-page' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                        {{ cart|length }}
                    </a>
                    {% if not request.user.restaurant %}
                        <a class="dropdown-item" href="{% url 'restaurant:register-restaurant' %}">Register Restaurant</a>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'accounts:request-list' %}">Requests</a>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                </div>
          </li>
          {% else %}
          <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
          <a class="btn btn-outline-primary"
            href="{% url 'account_signup' %}">Sign Up</a>
        {% endif %}
      </nav>
    </div>